spring:
  datasource:
    url: jdbc:h2:file:./db/spring-boot-project-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: ALWAYS