server:
  port: 8080
  error:
    include-message: ALWAYS

spring:
  datasource:
    url: jdbc:h2:file:./car-industry/db/car-info-service-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      car-info-service:
        opaque:
          introspection-uri: http://localhost:8079/auth/realms/car-industry/protocol/openid-connect/token/introspect
          introspection-client-id: car-info-service-client
          introspection-client-secret: car-info-service-secret
